services: 
  db:
    image: postgres
    ports:
      - 5002:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urna-eletronica-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: